SELECT SUM(gr.SCORE) SCORE, gr.EMP_NO EMP_NO, he.EMP_NAME EMP_NAME, he.POSITION POSITION, he.EMAIL EMAIL
FROM HR_GRADE gr
JOIN HR_EMPLOYEES he
ON gr.EMP_NO = he.EMP_NO
WHERE gr.YEAR = 2022
GROUP BY gr.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
